### ISSUE TITLE
alt attribute missing

### ISSUE THREAD

**Issue by miguelangeltorresfp** [peterlazzarino/react-adaptive-image#12] opened 2019-03-17 13:39 UTC
Hi, this is my first issue ever here in github.

I'm not sure, but I think there's a typo and the "alt" attribute is not passed correctly to the final image component.

Suggestion : Add a class "loaded" to the image to facilitate a css transition effect from a background color when the loading process finishes.

Thank you anyway for this amazing library.

**Comment by peterlazzarino** [comment] 2019-03-18 19:51
@miguelangeltorresfp thanks for reporting this 😄, I will take a look at this this week and let you know when I publish a fix

**Comment by miguelangeltorresfp** [comment] 2019-03-18 22:16
Thanks @peterlazzarino for sharing your time and knowledge.

If you don't mind and have time, please, check also if the preload option works as expected. It doesn't work for me but I think it's because I'm using it inside the react-scroll-parallax.

But anyway, the images load perfectly scaled from Cloudinary and for a beginner like me it's a very easy solution.

Thank you again.

**Comment by peterlazzarino** [comment] 2019-03-19 02:06
Glad you like it! Do you have a repo that reproduces the issue with react-scroll-paralax? Right now scroll events aren't tracked in divs, just at the document level. Could be added though

**Comment by miguelangeltorresfp** [comment] 2019-03-23 00:13
Hi @peterlazzarino, sorry for my late response.
Right now I'm working on a private repo, but today I could take time to set up a test project with react-scroll-parallax and react-adaptive-image.
Images are loaded from Cloudinary and the project is on next.js framework.

Well, so far everything seems to work perfectly. I'll try to do more tests.

https://github.com/miguelangeltorresfp/react-adaptive-image-parallax-test

**Comment by peterlazzarino** [comment] 2019-03-26 15:15
Hey sorry havent had a chance to take a look at this yet, gonna check it out in the next few days!

**Comment by cloetensbrecht** [comment] 2020-10-29 19:56
This seems to be solved? An altText is available: https://github.com/peterlazzarino/react-adaptive-image#alttext

**Comment by peterlazzarino** [comment] 2020-11-10 15:37
yep @cloetensbrecht thanks for noticing! Im going to close this.

**Closed as completed by peterlazzarino** 2020-11-10 15:37 UTC
